name: Render resume.pdf
on: push
jobs:
  render-resume:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: typst-community/setup-typst@v4
        with:
          local-packages: packages.json
      - run: typst compile resume.typ resume.pdf --font-path assets/fonts
      - uses: actions/upload-artifact@v4
        with:
          name: resume
          path: resume.pdf
        
